query getPosts {
  posts(first: 200) {
    nodes {
      id
      slug
      title
      content
      categories {
        nodes {
          categoryId
        }
      }
      featuredImage {
        node {
          sourceUrl(size: THUMBNAIL)
        }
      }
      seo {
        canonical
        cornerstone
        focuskw
        metaDesc
        metaKeywords
        metaRobotsNofollow
        metaRobotsNoindex
        opengraphAuthor
        opengraphDescription
        opengraphModifiedTime
        opengraphPublishedTime
        opengraphPublisher
        opengraphSiteName
        opengraphTitle
        opengraphType
        opengraphUrl
        title
        twitterDescription
        twitterTitle
      }
    }
  }
}
